language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
script:
  - coverage run --source=go_auth `which trial` go_contacts
after_success:
  - coveralls
