language: python
python:
  - "2.6"
  - "2.7"
services:
  - riak
before_install:
  # we need the protobuf-compiler so we can install Riak client libraries
  - sudo apt-get install -qq protobuf-compiler
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
script:
  - coverage run --source=go_contacts `which trial` go_contacts
after_success:
  - coveralls
